spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username : root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    history-level: full
    db-history-used: true
  security:
    filter:
      dispatcher-types:


mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:com/test/activiti/mapper/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.test.activiti.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      db-type: mysql

logging:
  level:
    com:
      test:
        activiti:
          mapper: debug